tsutsu3/pi-hole-client

- lib/base.dart
- lib/constants/responsive.dart
- lib/screens/domains/domain_tile.dart
- lib/screens/domains/domains.dart
- lib/screens/domains/domains_list.dart
- lib/screens/home/home.dart
- lib/screens/home/home_charts.dart
- lib/screens/logs/log_tile.dart
- lib/screens/logs/logs.dart
- lib/screens/logs/logs_filters_modal.dart
- lib/screens/servers/servers.dart
- lib/screens/servers/servers_tile_item.dart
- lib/screens/settings/app_settings/advanced_settings/advanced_options.dart
- lib/screens/settings/settings.dart
- lib/screens/statistics/statistics.dart
- lib/screens/statistics/statistics_queries_servers_tab.dart
- lib/screens/unlock.dart
- lib/widgets/no_server_selected.dart
- lib/widgets/numeric_pad.dart
- test/widgets/domains/domains_test.dart
- test/widgets/logs/logs_test.dart
|small (<700)| medium (<900) | large |
|----|----|----|
|![s](https://github.com/user-attachments/assets/3f27fa6f-f080-4e9a-bdb2-6d4f777399db)|![ml](https://github.com/user-attachments/assets/89ee2ec7-df44-41b4-afb7-a3460f8fd69c)|![l](https://github.com/user-attachments/assets/fc91be85-034a-44d7-9515-4fe180c03187)|
> refactor(responsive): unify breakpoint names to small, medium, large, xLarge, xxLarge

- lib/functions/graph.dart
- lib/screens/home/widgets/clients_last_hours_line.dart
- lib/screens/home/widgets/queries_last_hours_line.dart
> fix(graph): resolve home graph issues

- lib/screens/servers/add_server_fullscreen.dart
This update temporarily disables updates for HTTP/HTTPS and v5/v6.  
A fundamental solution will be implemented in #109 
Allowed modifications only for server name and password now.
**Changes:**  
- Disabled updates for HTTP/HTTPS and v5/v6 to prevent unintended modifications.  
- This is a temporary measure until a proper fix is applied.  
**Next Steps:**  
- Implement a fundamental solution in #109
> fix(edit_server): temporarily disable the changes

- lib/base.dart
- lib/pi_hole_client.dart
This PR optimizes state management by ensuring that widgets subscribe only to the specific provider properties they require. Instead of subscribing to the entire provider, we now leverage Consumer and Selector widgets to limit rebuilds strictly to the parts of the UI that depend on the changed data.
Refactored Provider Subscriptions:
Modified widgets to use Consumer/Selector to listen only to required properties, reducing unnecessary rebuilds.
> perf(pi_hole_client): subscribe only to necessary provider properties

- lib/models/repository/database.dart
This PR fixes an issue where the app crashes on startup due to a type mismatch when reading the `logsPerQuery` field from the database.  
- Updated the `fromMap` method to use `(map['logsPerQuery']! as num).toDouble()` instead of `as int`.
> fix(database): change logsPerQuery type from int to double

- lib/screens/servers/servers.dart
- lib/screens/settings/app_settings/language_screen.dart
- lib/screens/settings/app_settings/theme_screen.dart
- Converted LanguageScreen and ThemeScreen to StatelessWidgets
- Added WillPopScope to ensure the Android back gesture (system back navigation) correctly navigates back to the Settings screen on smartphones.
(Tablet layout is not yet supported.)
This PR only applies to smartphone layouts.
Tablet layout adjustments for WillPopScope are not yet included and require further consideration.
#158
> feat(ui): convert LanguageScreen & ThemeScreen to stateless, fix back gesture behavior (Mobile layout is not yet)

- lib/screens/servers/servers_tile_item.dart
close #194 
However, there is a brief flicker.
This occurs because after selecting a server, the navigation bar highlight moves from Statistics to Settings, making the transition appear as a flicker.
This issue will be addressed in a future update to ensure a smoother transition.
> fix(settings): prevent navigation to home after selecting server

- lib/screens/home/home_appbar.dart
This PR enhances the visual indication for the server switching functionality .
- Use InkWell
- Add `sync_alt_rounded` icon
- Positioned the icon on the right side
> feat(home): improve server switch indication

- .github/workflows/release.yaml
- README.md
- debian/scripts/postrm
- debian/scripts/preinst
- docs/development.md
- docs/install.md
- Add preinst
- Add postrm
- Add installation guide
https://github.com/tsutsu3/pi-hole-client/actions/runs/13871215791/artifacts/2757301494
> fix(debian): resolve dpkg warning when removing piholeclient

- lib/services/status_update_service.dart
- test/ut/services/status_update_service_test.dart
Fixes a null check error by ensuring asynchronous operations always reference the correct server instance.
- Captured the current server state in a local variable before async processing.
- Compared the captured server address with the current one before applying state updates.
> fix(status_update_service):prevent null check error by capturing current server state

- lib/base.dart
- lib/gateways/v6/api_gateway_v6.dart
- lib/main.dart
- lib/services/status_update_service.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR addresses an issue where excessive web sessions were being created when interacting with Pi-hole v6, leading to session limit violations and blocked requests.　The fix optimizes session management to prevent exceeding the session limit.  
Additionally, this change resolves an issue where "No data" was temporarily displayed when the app was resumed.
- Pause auto-update when the app moves to the background.  
- Resume auto-update when the app returns to the foreground.  
- If a default server is configured, the app performs authentication before fetching data.  
- Ensure that only one active session is maintained to prevent exceeding Pi-hole’s session limit.  
| No. | Platform  | Default | Session Status | App State | Session Count | …
> fix(status_update_service): reduce excessive web sessions on Pi-hole v6

- lib/main.dart
- lib/providers/app_config_provider.dart
- lib/repository/database.dart
- lib/screens/settings/app_settings/advanced_settings/advanced_options.dart
- test/ut/helper.dart
- test/ut/providers/app_config_provider_test.dart
- test/ut/repository/database_test.dart
- test/widgets/helpers.dart
Previously, SSL certificate verification was enabled by default. With this change, SSL verification is now **disabled by default**.  
- Pi-hole v6 now supports HTTPS connections with self-signed certificates by default.  
- There have been multiple user reports about connection issues when trying to connect via HTTPS, especially due to self-signed certificates.  
- To improve user experience and reduce confusion, we are changing the default behavior to **disable** SSL certificate verification unless explicitly enabled by the user.  
- The default value of `Don't check SSL Certificate` is now **true** (previously **false**).  
- Users who require strict SSL verification should manually disable `Don't check SSL Certificate` in the settings.  
- **Breaking Change:** Users who expect SSL …
> feat(ssl): change default value of overrideSslCheck to true

- lib/screens/settings/server_settings/server_info.dart
- test/widgets/screens/settings/server_settings/server_info_test.dart
This PR improves error handling on the Pi-hole server screen. If fetching server information fails, an ErrorMessageScreen is displayed to inform users of the issue.
- Added error handling for failed server info retrieval.
- Displays an ErrorMessageScreen when fetching server info fails.
> fix(server_info): handle server info fetch failure in ServerInfoScreen

- debian/scripts/postrm
- windows/innosetup_installer_builder.iss
This PR improves the uninstall process by implementing platform-specific behavior for user data cleanup:
User-specific data such as SQLite databases and secure storage files are **automatically deleted** during uninstallation, since the app and data are stored in the user’s own profile and are not shared.
User data is **not deleted automatically**, as the application is typically shared across users. Instead, a warning message is displayed during uninstall, guiding users to manually delete their own data if needed. KDE users are also informed about potential remaining secrets in KWallet.
- Added code to delete:
- `%LOCALAPPDATA%\Programs\Pi-hole client`
- `%APPDATA%\io.github.tsutsu3\Pi-hole client`
- Retained `/usr/local/lib/PiHoleClient` deletion
- Added user-facing warning about …
> feat(uninstaller): delete user data on Windows, show warning only on Linux

- lib/screens/settings/server_settings/server_info.dart
This PR fixes a potential crash in `ServerInfoScreen` that could occur when `selectedServer` or `selectedApiGateway` is `null`.
- Added null checks at the beginning of `build()` to show `EmptyDataScreen` when no server is selected
> fix(server_info): avoid null crash in ServerInfoScreen when no server is selected

- lib/screens/app_logs/app_logs.dart
- lib/screens/domains/domain_details_screen.dart
- lib/screens/domains/domains_list.dart
- lib/screens/home/home.dart
- lib/screens/home/home_appbar.dart
- lib/screens/logs/logs.dart
- lib/screens/logs/logs_filters_modal.dart
- lib/screens/servers/add_server_fullscreen.dart
- lib/screens/servers/servers.dart
- lib/screens/servers/servers_tile_item.dart
- lib/screens/settings/app_settings/advanced_settings/advanced_options.dart
- lib/screens/settings/app_settings/advanced_settings/app_unlock_setup_modal.dart
- lib/screens/settings/server_settings/widgets/subscriptions/subscription_details_screen.dart
- lib/screens/settings/server_settings/widgets/subscriptions/subscriptions_list.dart
This PR fixes an issue where pressing the system back button while a dialog is open would cause the app to exit unexpectedly.
- Added `useRootNavigator: false` to the `showDialog` call
- Home
- Switch server
- Disable
- Logs
- Filters
- Domains
- Add domain
- Delete domain
- Domain Comment
- Advenced settings
- App unlock
#158
> fix(dialog): useRootNavigator false to handle back navigation correctly on mobile

- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_ja.arb
- lib/l10n/app_pl.arb
- lib/l10n/generated/app_localizations.dart
- lib/l10n/generated/app_localizations_de.dart
- lib/l10n/generated/app_localizations_en.dart
- lib/l10n/generated/app_localizations_es.dart
- lib/l10n/generated/app_localizations_ja.dart
- lib/l10n/generated/app_localizations_pl.dart
- lib/screens/servers/add_server_fullscreen.dart
- test/widgets/screens/servers/add_server_fullscreen_test.dart
Moved the subroute setting to the bottom of the **Connection Settings** section and placed it inside an accordion. This helps reduce visual clutter by hiding advanced options by default. Padding has also been adjusted for consistency with other form fields.
- Moved subroute field to the bottom of the connection section
- Wrapped the subroute setting inside an `ExpansionTile` (accordion)
- Adjusted padding around the subroute input for layout consistency
> feat(server): move optional subroute settings to bottom and wrap in accordion

- lib/screens/logs/logs_filters_modal.dart
- lib/screens/settings/app_settings/advanced_settings/app_unlock_setup_modal.dart
This PR fixes an issue where footer buttons (e.g., OK / Close) in `LogsFiltersModal` and `AppUnlockSetupModal` were not fixed at the bottom and could scroll out of view on smaller screens or with long content.
- Updated layout to use `Column` with `Flexible + SingleChildScrollView` for scrollable content and fixed footer
- Improved overall user experience by keeping footer buttons always visible and accessible
> fix(scroll): keep footer buttons fixed at the bottom

- lib/models/overtime_data.dart
|before|after|
|---|---|
|![before](https://github.com/user-attachments/assets/96428d7a-d681-4426-96d5-269a4969a420)|![after](https://github.com/user-attachments/assets/53a2b96b-74b9-4563-8f40-09c90a8f4ec7)|
> fix(overtime_data): handle null client names by providing an empty string

- lib/models/api/v6/ftl/system.dart
- lib/models/api/v6/ftl/system.freezed.dart
- lib/models/api/v6/ftl/system.g.dart
- lib/models/system.dart
- test/ut/gateways/v6/api_gateway_v6_test.dart
This PR adds an optional percentCpu field to the CPU model, mapped from the %cpu key introduced in FTL v6.1.
If the field is not present, the system will fallback to using the average CPU load as before.
> feat(model): support %cpu field from FTL v6.1

- lib/screens/statistics/statistics.dart
- lib/screens/statistics/statistics_list.dart
- lib/screens/statistics/statistics_queries_servers_tab.dart
- lib/widgets/tab_content.dart
This PR fixes a error caused by sharing the same `ScrollController` across multiple tabs using `CustomTabContent`. The issue occurred when switching between the "Domains" and "Clients" tabs and scrolling.
- Assigned separate `ScrollController`s to each tab.
- Updated components to accept optional controllers.
- Prevented multiple scroll views from using the same controller.
> fix(statistics): isolate ScrollControllers for each CustomTabContent

- lib/widgets/navigation_rail.dart
This PR addresses a layout issue where the CustomNavigationRail component would cause a bottom overflow error when the keyboard was opened, especially in landscape mode.
- Wrapped NavigationRail with LayoutBuilder to capture parent height constraints.
- Added a ConstrainedBox with minHeight to enforce minimum height behavior.
- Wrapped the entire structure in a SingleChildScrollView to enable scrolling when necessary.
|before|after|
|---|---|
|![Screenshot_1745669319](https://github.com/user-attachments/assets/5c7f2d75-6a0d-4993-8ad7-5c55dd6cf631)|![Screenshot_1745669297](https://github.com/user-attachments/assets/0dd555ad-22ce-4873-962b-fea2c9e3c796)|
- #96
> fix(navrail): prevent bottom overflow in CustomNavigationRail with scrollable layout

- lib/screens/logs/clients_filters_modal.dart
- lib/screens/logs/status_filters_modal.dart
Fix dialogs to keep action buttons (Check All, Close, Apply) always visible at the bottom, even when the list content is scrollable. Improves usability when working with long lists.
- Logs Status filter (logsStatus)
- Clients filter (clients)
|before|after|
|---|---|
|![Screenshot_1745728333](https://github.com/user-attachments/assets/e4b92896-532f-482f-81c5-4dc29cb487d9)|![Screenshot_1745728317](https://github.com/user-attachments/assets/0d5533ba-34f4-4340-a888-5964ee009333)|
- #96
> fix(logs_filter_modal): keep action buttons always visible in dialog

- lib/screens/domains/add_domain_modal.dart
- lib/screens/domains/domains_list.dart
- lib/screens/servers/add_server_fullscreen.dart
- lib/screens/settings/server_settings/widgets/subscriptions/add_subscription_modal.dart
- lib/screens/settings/server_settings/widgets/subscriptions/edit_subscription_modal.dart
- lib/screens/settings/server_settings/widgets/subscriptions/subscription_details_screen.dart
- lib/screens/settings/server_settings/widgets/subscriptions/subscriptions_list.dart
Adjusted padding behavior to prevent overflow when the keyboard is visible in landscape mode.
|before|after|
|---|---|
|![Screenshot_1745734731](https://github.com/user-attachments/assets/18692f76-516d-446d-88f9-841a7e0f5104)|![Screenshot_1745734741](https://github.com/user-attachments/assets/992a9ed0-e050-48d2-aeb2-d29e803d1cf0)|
|![Screenshot_1745734751](https://github.com/user-attachments/assets/6a7d388a-e070-409a-a704-9c0033a1f272)|![Screenshot_1745735429](https://github.com/user-attachments/assets/f1579fc8-c7ba-48ff-abb5-3d411ba1bf2c)|
close #96
> fix(modal): prevent bottom overflow when keyboard is visible in landscape

- lib/base.dart
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_ja.arb
- lib/l10n/app_pl.arb
- lib/l10n/generated/app_localizations.dart
- lib/l10n/generated/app_localizations_de.dart
- lib/l10n/generated/app_localizations_en.dart
- lib/l10n/generated/app_localizations_es.dart
- lib/l10n/generated/app_localizations_ja.dart
- lib/l10n/generated/app_localizations_pl.dart
- lib/main.dart
- lib/providers/servers_provider.dart
- lib/screens/servers/add_server_fullscreen.dart
- lib/services/status_update_service.dart
- test/ut/providers/domains_list_provider_test.mocks.dart
- test/ut/providers/filters_provider_test.mocks.dart
- test/ut/providers/gravity_provider_test.mocks.dart
- test/ut/providers/groups_provider_test.mocks.dart
- test/ut/providers/servers_provider_test.dart
- test/ut/providers/subscriptions_list_provider_test.mocks.dart
- test/ut/services/status_update_service_test.dart
- test/ut/services/status_update_service_test.mocks.dart
- test/widgets/helpers.dart
- test/widgets/helpers.mocks.dart
- test/widgets/screens/servers/add_server_fullscreen_test.dart
This PR enhances the **Edit a Connection** page by allowing users to modify additional connection settings that were previously read-only. These settings include SSL certificate handling and default server designation, improving configuration flexibility.
- Enabled editing of the following fields in the **Edit Connection** page:
- Allow self-signed certificates**
- Default connection**
|before|after|
|---|---|
|![before](https://github.com/user-attachments/assets/99e20215-fb42-4acd-a768-0a4618cc4920)|![after](https://github.com/user-attachments/assets/abc45c37-c5ce-49ef-ae6e-0c195e59bb1e)|
> feat(servers): allow editing default connection and SSL cert options on edit page

- lib/functions/charts_data_functions.dart
- lib/screens/statistics/no_data_chart.dart
- lib/screens/statistics/statistics_list.dart
- test/widgets/screens/statistics/statistics_test.dart
This PR improves the visual layout  of the `NoDataChart` component, used in both the **Home** and **Statistics** screens. 
- Added a light background tint and border with rounded corners to enhance the visual clarity of the empty chart area.
- Passed correct localized section titles (e.g., "Top Clients", "Top Permitted Domains") instead of using "No data" as a placeholder.
- Home
- Statistics (Top Clients, Top Blocked Domains, etc.)
|beafore|after|
|---|---|
|![before](https://github.com/user-attachments/assets/a624b13c-8daf-436f-b00f-81c9722b8f88)|![after](https://github.com/user-attachments/assets/1c884d3e-8413-4685-9000-f3b7ea0b4197)|
> feat(ui): improve NoDataChart layout and section labeling on home and statistics pages

- lib/screens/domains/widgets/domain_details_screen.dart
Update `Date addted` and `Date modified` icons.
|before|after|
|---|---|
|![Screenshot_1747655502](https://github.com/user-attachments/assets/5a70aa29-04a1-4a89-ab10-efc1f03b7f43)|![Screenshot_1747655493](https://github.com/user-attachments/assets/1416d34a-179a-4674-8bba-5e1274c3b2d3)|
> chore(ui): replace icons in domain detail screen

- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_ja.arb
- lib/l10n/app_pl.arb
- lib/l10n/generated/app_localizations.dart
- lib/l10n/generated/app_localizations_de.dart
- lib/l10n/generated/app_localizations_en.dart
- lib/l10n/generated/app_localizations_es.dart
- lib/l10n/generated/app_localizations_ja.dart
- lib/l10n/generated/app_localizations_pl.dart
- lib/screens/settings/app_settings/advanced_settings/auto_refresh_time_screen.dart
- lib/screens/settings/app_settings/advanced_settings/logs_quantity_load_screen.dart
- test/widgets/screens/settings/app_settings/auto_refresh_time_screen_test.dart
This PR improves the user experience on the Advanced Settings screen by enabling auto-save for two key configuration fields:
- Auto Refresh Time
- Logs Quantity Per Request
Manual save buttons have been removed. Changes are now saved automatically when the user enters valid input or moves focus away from the field.
- Removed the save button previously used for these fields.
- Enabled real-time validation and saving
|before|after|
|---|---|
|![before](https://github.com/user-attachments/assets/b1684112-54d9-4be9-abee-0a094e366874)|![after](https://github.com/user-attachments/assets/38421d3e-ce49-4ac2-89b1-b32554926dd6)|
> feat(ui): enable auto-save for refresh interval and log quantity in advanced settings

- lib/constants/formats.dart
- lib/functions/format.dart
- lib/functions/logger.dart
- lib/screens/domains/widgets/domain_details_screen.dart
- lib/screens/domains/widgets/domain_tile.dart
- lib/screens/logs/logs_filters_modal.dart
- lib/screens/logs/no_logs_message.dart
- lib/screens/settings/server_settings/widgets/subscriptions/subscription_details_screen.dart
Unified datetime display format to yyyy-MM-dd in the logs screen.
|before|after|
|---|---|
|![before](https://github.com/user-attachments/assets/57d82956-3289-4eff-8754-d1615c067c1b)|![after](https://github.com/user-attachments/assets/00a733d4-5df1-4750-9cd3-5502d87f7574)|
> style(logs): unify datetime display format to yyyy-MM-dd

- lib/base.dart
- lib/functions/refresh_server_status.dart
- lib/functions/server_management.dart
- lib/functions/snackbar.dart
- lib/main.dart
- lib/screens/app_logs/app_logs.dart
- lib/screens/domains/domains.dart
- lib/screens/domains/widgets/domains_list.dart
- lib/screens/home/home.dart
- lib/screens/home/widgets/home_appbar.dart
- lib/screens/logs/logs.dart
- lib/screens/logs/logs_filters_modal.dart
- lib/screens/servers/add_server_fullscreen.dart
- lib/screens/servers/servers.dart
- lib/screens/servers/servers_list.dart
- lib/screens/servers/servers_tile_item.dart
- lib/screens/settings/app_settings/advanced_settings/app_lock/create_pass_code_modal.dart
- lib/screens/settings/app_settings/advanced_settings/app_lock/remove_passcode_modal.dart
- lib/screens/settings/app_settings/advanced_settings/app_unlock_setup_modal.dart
- lib/screens/settings/app_settings/advanced_settings/enter_passcode_modal.dart
- lib/screens/unlock.dart
- lib/widgets/start_warning_modal.dart
The primary purpose of this PR is to **remove** the directive:
```dart
// ignore_for_file: use_build_context_synchronously
```
and instead adopt **explicit `context.mounted` checks** after asynchronous operations, to ensure safe and predictable usage of `BuildContext` throughout the app.
As a side benefit, it also **helps mitigate the crash reported in Sentry**:
> **TypeError: Null check operator used on a null value**
> Location: `snackbar.dart` at line 86
which likely resulted from unsafe context access after widget disposal.
* Removed all instances of `// ignore_for_file: use_build_context_synchronously`
* Added `if (!context.mounted) return;` after `await` calls that precede context usage
> fix(context): ensure safe usage with context.mounted checks

- lib/main.dart
- lib/providers/app_config_provider.dart
This PR adds safeguards around the use of `LocalAuthentication` to prevent crashes on certain Android environments  where biometric APIs may behave unexpectedly or be partially unsupported.
* Added a check for `auth.isDeviceSupported()` before attempting any biometric operations
* Wrapped `auth.getAvailableBiometrics()` in a separate `try-catch` block to avoid crashing on unstable implementations
* Checked for valid `BiometricType`s; if none are available, `configProvider.setUseBiometrics(false)` is applied
* Wrapped the entire biometric logic in a top-level `try` block to ensure app stability even in case of unexpected errors
These changes improve app robustness and ensure that biometric features degrade gracefully on unsupported or unstable devices.
> fix: improve robustness of biometric and device info initialization

- lib/providers/subscriptions_list_provider.dart
- lib/screens/settings/server_settings/subscriptions.dart
- test/ut/providers/subscriptions_list_provider_test.dart
This PR resolves an issue where stale subscription data briefly appears on the screen after switching servers.
> fix(adlist): show loading indicator on subscription screen to prevent stale data flash

- lib/functions/misc.dart
- lib/gateways/api_gateway_interface.dart
- lib/gateways/v5/api_gateway_v5.dart
- lib/gateways/v6/api_gateway_v6.dart
- lib/providers/servers_provider.dart
Improve stability of realtimeStatus by splitting requests into two batches to avoid connection errors under heavy load.
- Split 8 parallel requests into 2 batches of 4.
> fix(api): improve realtimeStatus stability by splitting requests into batches

- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/l10n/app_ja.arb
- lib/l10n/app_pl.arb
- lib/l10n/generated/app_localizations.dart
- lib/l10n/generated/app_localizations_de.dart
- lib/l10n/generated/app_localizations_en.dart
- lib/l10n/generated/app_localizations_es.dart
- lib/l10n/generated/app_localizations_ja.dart
- lib/l10n/generated/app_localizations_pl.dart
- lib/providers/domains_list_provider.dart
- lib/screens/domains/domains.dart
- lib/screens/domains/widgets/domains_list.dart
- test/ut/providers/domains_list_provider_test.dart
- test/widgets/screens/domains/domains_test.dart
This PR fixes a bug where the "Domains" screen sometimes displayed outdated domain data from a previously selected server after switching servers.
- Set `LoadStatus.loading` immediately when switching servers to ensure a proper loading state is shown.
- Added missing `notifyListeners()` call in `setLoadingStatus()` to ensure UI updates when the loading status changes.
- Updated loading message from "Loading list..." to "Loading domains..." for better clarity.
- Updated related unit tests to reflect the updated behavior of `setLoadingStatus()`.
> fix(domains): show loading state when switching servers to prevent outdated domain data

- lib/functions/refresh_server_status.dart
- lib/gateways/api_gateway_interface.dart
- lib/gateways/v5/api_gateway_v5.dart
- lib/gateways/v6/api_gateway_v6.dart
- lib/screens/home/widgets/home_appbar.dart
- lib/screens/logs/log_details_screen.dart
- lib/screens/servers/servers_tile_item.dart
- lib/screens/statistics/statistics_list.dart
- lib/services/status_update_service.dart
- test/ut/gateways/v6/api_gateway_v6_test.dart
- test/ut/providers/domains_list_provider_test.mocks.dart
- test/ut/providers/gravity_provider_test.mocks.dart
- test/ut/providers/groups_provider_test.mocks.dart
- test/ut/providers/subscriptions_list_provider_test.mocks.dart
- test/ut/services/status_update_service_test.dart
- test/ut/services/status_update_service_test.mocks.dart
- test/widgets/helpers.dart
- test/widgets/helpers.mocks.dart
Partially addresses issue #313 
This PR resolves an issue where the Query Log would only display the top 9 clients. The "other clients" filter previously failed to load additional clients and their queries. This fix ensures all clients are displayed and the filter functions as expected.
- Updated Query Log client list retrieval to include all clients.
- Switched client list source from `fetchOverTimeData`to `realtimeStatus`.
- Delete `other clients`
> fix(log): display all clients

- lib/screens/settings/server_settings/advanced_settings/sessions_screen.dart
- lib/screens/settings/server_settings/advanced_settings/sessions_screen/session_list_view.dart
- test/full_coverage_test.dart
This PR improves the user experience of the **Session Screen** (located in *Settings > Advanced > Sessions*) by replacing the existing loading spinner (`CircularProgressIndicator`) with a **skeleton-based placeholder** using the `skeletonizer` package.
This makes the loading state more visually informative and consistent with other parts of the app that use skeleton loading patterns.
* Replaced the loading spinner with a `Skeletonizer` + `SessionListView` using fake data.
* Extracted session list rendering logic into a dedicated `SessionListView` widget.
* Removed inline `buildStatusIcon` and `buildTlsLine` from `SessionsScreen`, as they're now encapsulated in `SessionListView`.
|before|after|
|---|---|
|![before](https://github.com/user-attachments/assets/ce0c55d4-b547-428f-8c33-64654c828 …
> feat(settings/session): use skeleton loader instead of spinner

- lib/screens/settings/server_settings/advanced_settings/network_screen.dart
- lib/screens/settings/server_settings/advanced_settings/network_screen/network_list_view.dart
- test/full_coverage_test.dart
This PR improves the user experience of the **Network Screen** (located in *Settings > Advanced > Network*) by replacing the existing loading spinner (`CircularProgressIndicator`) with a **skeleton-based placeholder** using the `skeletonizer` package.
This makes the loading state more visually informative and consistent with other parts of the app that use skeleton loading patterns.
* Replaced the loading spinner with a `Skeletonizer` + `SessionListView` using fake data.
* Extracted session list rendering logic into a dedicated `SessionListView` widget.
* Removed inline `buildStatusIcon` and `buildDeviceTitle` from `NetworkScreen`, as they're now encapsulated in `NetworkListView`.
|before|after|
|---|---|
|![before](https://github.com/user-attachments/assets/efad47c2-7664-4115-8e87-981c2ce …
> feat(settings/netowork): use skeleton loader instead of spinner

- lib/screens/home/widgets/home_appbar.dart
- lib/services/status_update_service.dart
This pull request addresses a compatibility issue with Pi-hole v5.
In version 5, the metrics API endpoint returns `APiResponseType.notSupported`, which was previously unhandled. As a result, the UI status indicator would remain stuck or delayed after a server switch, giving the impression that no update occurred.
By explicitly handling the `notSupported` response, we ensure that the system gracefully skips metric updates when unsupported — avoiding misleading UI feedback.
* Added explicit handling for `APiResponseType.notSupported` in the metrics fetch logic
* Treated unsupported responses as a non-blocking success (`return true`)
> fix(home): resolved delayed status feedback on server change in v5

- lib/screens/home/widgets/home_tiles.dart
- lib/screens/home/widgets/home_tiles/home_tile.dart
- lib/screens/settings/server_settings/advanced_server_options.dart
- test/widgets/screens/home/home_test.dart
Tapping on a dashboard tile now leads the user directly to the relevant screen for that metric or function.
- Enabled tap-to-navigate behavior for dashboard tiles:
- Total queries → navigates to NetworkScreen
- Queries blocked → navigates to LogsScreen with block filter ON
- Percentage blocked → navigates to LogsScreen with block filter ON
- Domains on Adlists → navigates to AdlistsScreen
> feat(home): tap tile to navigate to corresponding screen

- lib/providers/servers_provider.dart
- lib/screens/servers/servers_list.dart
Fixed an issue where the server tile was not displayed immediately after adding a server.
> fix(server): show server tile immediately after adding by recreating list for context.select()

- lib/functions/misc.dart
- lib/screens/home/widgets/home_appbar/server_label.dart
- lib/screens/servers/servers_tile_item_controller.dart
- lib/services/status_update_service.dart
- test/widgets/helpers.mocks.dart
This PR fixes an issue where certain API requests (`status` and `overtime`) were being triggered twice at nearly the same time.  
- Removed redundant or overlapping calls to `realtimeStatus` and `fetchOverTimeData`
```plaintext
ClientException: Connection closed before full header was received, uri=https://192.168.11.3/api/history
#0      IOClient.send (package:http/src/io_client.dart:156:7)
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:1064:7)
#3      ApiGatewayV6.httpClient (package:pi_hole_client/gateways/v6/api_gateway_v6.dart:174:24)
#4      ApiGatewayV6.fetchOverTimeData (package:pi_hole_client/gateways/v6/api_gateway_v6.dart:561:24)
#5 …
```
> fix(home): remove redundant near-simultaneous duplicate calls

- android/app/src/main/AndroidManifest.xml
- lib/services/status_update_service.dart
- test/ut/services/status_update_service_test.dart
This pull request fixes a network-related error and a UI bug in the server status indicator. The changes improve connection reliability during auto-refresh and ensure the status icon correctly updates after recovery from an error state.
- Reduced the auto-refresh interval by 300ms to prevent ClientException: Connection closed before full header was received, which occurred on specific devices like Pixel 6a.
- Fixed an issue where the server status icon did not reset correctly after recovering from an error.
> fix(auto_refresh): avoid 'Connection closed before full header was received' on specific devices

- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
> Please do not use this SDK version if you're initializing the SDK manually on a background thread, as this could lead to a crash during SDK init. We recommend using SDK version 8.13.1 or higher instead. Checkout our releases page for more details: https://github.com/getsentry/sentry-java/releases
> chore(sentry): upgrade to v9.4.0 to avoid crash on manual Android init

- lib/ui/home/home.dart
Fix FAB overlapping SnackBar on small screens and ensure it returns to its original position after dismissal.
- Observe AppConfigProvider.showingSnackbar via context.select for reactive FAB updates.
- Centralize FAB bottom offset logic in calcFabPosition().
- Use dynamic offsets: 100.0 when Snackbar visible on narrow screens (width <= ResponsiveConstants.medium), else 70.0; default 20.0 when hidden.
> fix(home): ensure FAB position resets after snackbar dismissal
